import { LeadDoctor, Doctor } from "@/types/doctor"

export const leadDoctor: LeadDoctor = {
    id: "dr-shaivalini",
    name: "Dr. Shaivalini Kamarapu",
    designation: "Senior Cosmetic Gynaecologist, Fertility Specialist & Robotic Surgeon",
    tagline: "Hyderabad's Trusted IVF Specialist & Gynaecologist",
    experience: "20+",
    image: "/images/doctor/dr-shaivalini.png",
    bio: "Dr. Shaivalini Kamarapu is a renowned Senior Cosmetic Gynaecologist, Fertility Specialist, and Advanced Laparoscopic & Robotic Surgeon in Hyderabad, with over 20 years of experience in women's health, reproductive medicine and minimally invasive surgery. Recognised as one of the leading robotic gynaecological surgeons in Hyderabad, she has performed more than 100 robotic procedures using the SSi Mantra Surgical Robotic System, alongside over 1,000 complex gynaecological, cosmetic, laparoscopic and robotic surgeries. She is associated with some of Hyderabad's most prestigious healthcare institutions, including Apollo Hospitals, Ankura Hospitals and Rainbow Hospitals, and founded AMVI Hospitals to bring accessible, evidence-based reproductive care to families across the city.",
    achievements: [
        "20+ years of experience across advanced laparoscopic surgery and infertility treatments, including IVF, ICSI, IUI and TESA.",
        "Skilled in laparoscopic and hysteroscopic procedures — diagnostic and operative hysteroscopy, tubal recanalization, ovarian cystectomy, laparoscopic myomectomy and total laparoscopic hysterectomy.",
        "One of the few gynaecologists certified in cosmetic gynaecology, trained under specialists from the USA, France, Poland, India and Morocco.",
        "Exclusively specialises in vaginal laser surgery, including vaginoplasty, labiaplasty, hymenoplasty and laser vaginal rejuvenation.",
        "Visiting Assistant Professor at RVM Medical College, and previously served at a government hospital in Warangal.",
        "Active in clinical research, with national and international publications and conference faculty appearances.",
    ],
    research:
        "Clinical Study of Maternal and Perinatal Outcome in Relation to Birth Spacing Less Than Two Years and 2–4 Years",
    memberships: ["FOGSI", "American Association of Gynaecologic Laparoscopists", "IMA – Hyderabad"],
    expertise: [
        "IVF", "IUI", "ICSI", "PCOS / PCOD Management", "High-Risk Pregnancy",
        "Normal & Painless Delivery", "Laparoscopic Surgery", "Women's Health & Gynaecology",
    ],
    stats: [
        { label: "Surgeries performed", value: 1000, suffix: "+" },
        { label: "Robotic procedures", value: 100, suffix: "+" },
        { label: "Deliveries", value: 5000, suffix: "+" },
    ],
}

export const doctors: Doctor[] = [
    {
        id: "dr-gita-krishna",
        name: "Dr. P Gita Krishna",
        designation: "MBBS, MDRD — Consultant Radiologist",
        experience: "12+",
        image: "/images/doctor/dr-sushmita.png",
        bio: "A senior interventional radiologist specialising in Doppler scans in pregnancy, growth scans, TIFFA and anomaly scans, and 3D/4D ultrasound — regarded as one of Hyderabad's leading radiologists for prenatal imaging.",
    },
    {
        id: "dr-ganesh",
        name: "Dr. Ganesh",
        designation: "MBBS, MD — Paediatrician",
        experience: "25+",
        image: "/images/doctor/dr-sushmita.png",
        bio: "A senior consultant paediatrician with expertise in infant growth and development, newborn care, vaccination and behavioural disorders, including handling extreme preterm and preterm babies.",
    },
    {
        id: "dr-sumanth",
        name: "Dr. Sumanth",
        designation: "MD — Internal Medicine",
        experience: "12+",
        image: "/images/doctor/dr-sushmita.png",
        bio: "A patient-centred internal medicine physician focused on managing chronic conditions like diabetes, hypertension and heart disease, alongside acute illness and preventive care.",
    },
    {
        id: "dr-mohana-nandigam",
        name: "Dr. Mohana Nandigam",
        designation: "Clinical Psychologist",
        experience: "12+",
        image: "/images/doctor/dr-sushmita.png",
        bio: "Specialises in anxiety, depression and trauma through evidence-based approaches including cognitive-behavioural therapy, with comprehensive support spanning outpatient care to advanced treatments.",
    },
    {
        id: "sharanya-kamaraju",
        name: "Sharanya Kamaraju",
        designation: "Genetic Counselor",
        experience: "3+",
        image: "/images/doctor/dr-sushmita.png",
        bio: "A certified genetic counselor specialising in reproductive genetics, prenatal counseling, and paediatric neurogenetics and oncology, supporting families navigating complex genetic conditions.",
    },
    {
        id: "dr-s-manish",
        name: "Dr. S. Manish",
        designation: "Junior Embryologist",
        experience: "1+",
        image: "/images/doctor/dr-sushmita.png",
        bio: "Skilled in IVF lab procedures, embryo culture and laboratory protocols, contributing to successful outcomes through precision and scientific rigour.",
    },
    {
        id: "dr-divya",
        name: "Dr. Divya",
        designation: "Senior Anesthetist",
        experience: "10+",
        image: "/images/doctor/dr-sushmita.png",
        bio: "Extensive experience in obstetric and gynaecological anaesthesia, including painless epidural analgesia for labour and monitored anaesthesia care for infertility procedures.",
    },
    {
        id: "dr-sushmitha",
        name: "Dr. Sushmitha",
        designation: "Obstetrics & Gynaecology",
        experience: "3+",
        image: "/images/doctor/dr-sushmita.png",
        bio: "Completed DNB in Obstetrics & Gynaecology and a fellowship in Reproductive Medicine, with experience managing PCOS, endometriosis, tubal factors and poor ovarian reserve across the full IVF/ICSI spectrum.",
    },
    {
        id: "dr-jampani-ravitheja",
        name: "Dr. Jampani Ravitheja",
        designation: "Consultant Orthopedic Surgeon",
        experience: "8+",
        image: "/images/doctor/dr-sushmita.png",
        bio: "Specialises in knee and hip replacement, arthroscopy and trauma surgery, with more than 1,500 joint replacement surgeries and 3,000+ trauma and fracture surgeries performed.",
    },
    {
        id: "dr-gayathri",
        name: "Dr. Gayathri",
        designation: "Infertility Specialist",
        experience: "10+",
        image: "/images/doctor/dr-sushmita.png",
        bio: "Specialises in ovum pickups, embryo transfers, diagnostic hysteroscopy and D&C procedures, with a strong focus on counselling patients through the causes and options for infertility.",
    },
    {
        id: "dr-rajyalakshmi",
        name: "Dr. Rajyalakshmi",
        designation: "MBBS, MD — Consultant Physician",
        experience: "8+",
        image: "/images/doctor/dr-sushmita.png",
        bio: "A general physician experienced in treating hypertension, respiratory illness, allergies, asthma and infectious diseases.",
    },
    {
        id: "dr-priyanka-reddy",
        name: "Dr. Priyanka Reddy",
        designation: "MBBS, MS (OBG) — Obstetrician, Gynaecologist & Infertility Specialist",
        experience: "10+",
        image: "/images/doctor/dr-sushmita.png",
        bio: "Experienced in handling recurring IVF failures, PCOS-related infertility, male infertility and poor ovarian reserve, across IUI, IVF, ICSI, embryo cryopreservation and PGS/PGD.",
    },
]